### PR TITLE
Added to gitignore

### PR DESCRIPTION
**Pull request by blacksound**
Leave out build folder and .DS_Store files

### CODE REVIEW

**Comment by danstowell** [comment]
eirik, btw I think I've added you to the list of people with permission to directly commit. It's a good idea to keep working with PRs, but I've honestly no idea who will be the people actively working in the scvim repository

**Comment by blacksound** [comment]
Thanks Dan, I guess there are not that many active scvim users out there at the moment. But we can use this to at least report issues and document what needs to be done.

**Comment by dvzrv** [comment]
@blacksound well, I am one, for one :)
I'd like to change some more of the scvim code in the future, as well. Right now I don't have much time for it though trying to work on my thesis and all.
@danstowell would be great to be included somehow

**Comment by danstowell** [comment]
@dvzrv submit good PRs/issues and I'm sure a nice scvimmer such as Eirik will look at them and maybe merge them. That's inclusion already! If you don't have time then don't ;)

**Pull request merged**
