### PR TITLE
Basepath fix

### PR DESCRIPTION
**Pull request by dvzrv**
Fixes insufficient search for scvim plugin folder.
Documents the expected plugin folder location.
Adds vim-addon-manager to proposed tools.
Makes SCVim.initClass more robust.

### CODE REVIEW

**Comment by gusano** [comment]
@dvzrv I know it's a PITA but SCClassLibrary uses TABS (8 spaces) for indention.. That would make your PR/diff readable.

**Comment by dvzrv** [comment]
Oh God... has it come to this? I'm no fan :-(
Generally speaking, tabs are only a recommendation for the files included in SCClassLibrary and not a requirement, though, right?

**Comment by gusano** [comment]
@dvzrv Thanks. I agree it is dreadful but alas yes, it is a requirement *inside* SCClassLibrary

**Comment by dvzrv** [comment]
@gusano np. SuperCollider however will not break if there are spaces instead of tabs in SCClassLibrary files (I'm writing my classes exclusively using spaces).
Maybe it's necessary to add a code style file to this repository?

**Comment by gusano** [comment]
@dvzrv again agreed, but let's keep things consistent :)
(we're currently slowly adding a lint check for that, in the future build will fail if you propose unconsistent indention etc..)
Check scvim plugin files, they are also messy right now :)

**Comment by dvzrv** [comment]
@gusano will the linter just require proper intendation (which would be great, when thinking about stuff like python)? I hope it won't enforce the use of tabs on the users outside of the standard SCClassLibrary. That would be horrible.

Regarding the plugin files I recommend using spaces instead of tabs, though (I could do a retab, no problem! ;-)). Seems more like a standard in vimscript.

**Comment by gusano** [comment]
@dvzrv it wil inforce TABS in the library, spaces everywhere else IIRC.
This only applies to repo files.
User classes are freestyle and lint free :)

**Comment by dvzrv** [comment]
@gusano @blacksound can you please review? :)
It is a blocker for Linux systems. Who else is able to review/push this?

**Comment by gusano** [comment]
@dvzrv it's a blocker for vim-addons-manager users as it's (nearly) the only plugin who decided to put plugin folders in a place which differs from nearly all other plugin managers ;)
Will give your PR a try later today!

**Comment by dvzrv** [comment]
@gusano technically speaking, that is not entirely true. All of the managers allow putting plugins somewhere. scvim would break as soon as you deviate from the "norm" of installing stuff to standard folders (which all of them allow). My changes (hopefully) make loading more robust by not expecting just one form of naming scheme. Additionally it notifies users where things are expected to be (if they chose to install scvim to some other place and then wonder why it won't work).
Therefore, this is not a VAM issue alone.

However, it doesn't deal with system-wide installations (in the case of Linux), where vim plugins are installed somewhere under `/usr/share` (yet). Is there an equivalent for that under Mac OSX?

Thanks for trying it out!

**Comment by gusano** [comment]
@dvzrv Thanks!

**Pull request merged**
