### PR TITLE
Add a startup script that launches VIM and SCVIM inside of a TMUX session

### PR DESCRIPTION
**Pull request by madskjeldgaard**
Add a startup-file script inspired by tidalvim so that it's possible to start tmux, vim and SuperCollider using just one command: scvim

see https://github.com/munshkr/vim-tidal/blob/master/bin/tidalvim for more info

### CODE REVIEW

**Comment by datamads** [comment]
This needs some way to add the script as an environment variable or is it easier to just make a short doc in the readme describing the process on different platforms?

**Comment by dvzrv** [comment]
this approach is very atatic and can not encompass what users actually use out there. this way you will enforce tmux in everyone.

you can automatically start sclang on opening a *.{sc,scd} file in vim. If you really want a script, you can put it in your local overrides (e.g. a ~/bin).
However, making this a default is not advisable because of different workflows and no possible "sane default".

**Comment by datamads** [comment]
Ah okay that makes sense. What I'm concerned with though is I want to make it easier and more accessible for people who are new to VIM (and possibly the CLI as well) to get started with SCVIM and having a quick and easy way to open it – like tidalvim has – seemed like a good way to go. SC seems to attract a lot of people who don't have a lot of coding experience and thus probably no experience with VIM and it would be nice to make VIM a bit less daunting for them but maybe it's more a question of documentation then.

**Comment by capocasa** [comment]
That's a great idea to make vim more accessible!

A startup script is, however, too invasive, as has been pointed out- especially since scvim has historically been the name of  Also, I suspect that assuming familiarity with tmux would be counterproductive. I believe that your script would more appropriately be placed into the wiki as a tip, because it is useful in a very specific way.

**Pull request closed without merging**
