### PR TITLE
Improve syntax

### PR DESCRIPTION
**Pull request by mrzool**
This includes all SC class names in the syntax file so that they get properly highlighted. I might add commits later to highlight other things, like methods and such. Still have to look into it as I'm just getting started with SC.

Let me know what you think!

### CODE REVIEW

**Comment by snappizz** [comment]
Not an scvim user here, but wouldn't it be better to highlight all alphanumeric sequences in TitleCase?

**Comment by bagong** [comment]
.allClasses, and subsequently methods, is actually used in sc/SCVim.sc (line 73 ff). And it says deprecated in favor of "tags" (which uses ctags, which can do similar stuff as quick binary if you provide it a smart regex-file to parse the class files). @mrzool , I think the idea is to parse the language dynamically, so that the "syntax" (semi-)automatically adjusts to changes like the own code you add, extensions, different sc-versions and the like. I wonder what the status of that tags system is. I didn't get it to work on Linux (no .ctags file generated, :SCTags returns an error, SCVim.generateTagsFile() seeming to do something, but no feedback (and no .ctags file). Yes, I have ctags installed). I wonder what the status is: not working yet, undocumented install steps required, am I doing something wrong?

**Comment by gusano** [comment]
@mrzool I'm gonna close this as you already get it for free with `ctags`.

> I didn't get it to work on Linux (no .ctags file generated, :SCTags returns an error, SCVim.generateTagsFile() seeming to do something, but no feedback (and no .ctags file)

@bagong it works for me out of the box. Maybe open an issue with error etc?

**Comment by bagong** [comment]
If I enter :SCTags the error is something like "not known to scvim" or similar. You're sure I don't have to configure something for it to work, or open a specific document/type? I did get SCVim.generateTagsFile to work after a bit of trial and error, though. And now I realize it doesn't use ctags, right? SC does it itself.

**Comment by gusano** [comment]
> If I enter :SCTags the error is something like "not known to scvim" or similar

Would be nice to open a new issue about that ; )

> You're sure I don't have to configure something for it to work, or open a specific document/type?

Works out of the box for me within `scvim`, which means editing an `sc|scd` file

> And now I realize it doesn't use ctags, right? SC does it itself

sc generates `~/.sctags` file, but vim uses `ctags`, not sc.

**Comment by bagong** [comment]
Thanks for the explanation, @gusano !

**Comment by mrzool** [comment]
That's cool @gusano! Dynamically parsing the language is definitely a better solution than hard-coding every class name.

**Pull request closed without merging**
